### PR TITLE
Make ng2-uploader compatible with AoT Compiler

### PR DESCRIPTION
**Pull request by CelsoSantos**
Still need a version bump. Should I do it before accepting the PR or will someone take care of that after merging?

### CODE REVIEW

**Comment by jkuri** [comment]
please do that, then I'll merge and publish.

**Comment by jkuri** [comment]
@CelsoSantos if you need help with rebasing just say.

**Comment by theromis** [comment]
@jkuri after this update getting this errors
```
➜  ionic2 git:(master) ✗ npm update

> ng2-uploader@1.5.6 postinstall /opt/git/ionic2/node_modules/ng2-uploader
> ngc -p tsconfig.json

Error: Error Cannot find type definition file for 'node'.
    at Object.check (/opt/git/ionic2/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Object.main (/opt/git/ionic2/node_modules/@angular/tsc-wrapped/src/main.js:26:15)
    at Object.<anonymous> (/opt/git/ionic2/node_modules/@angular/compiler-cli/src/main.js:14:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
Compilation failed
```

**Comment by jkuri** [comment]
Just published 1.5.7. Can you check please @theromis?

**Comment by theromis** [comment]
@jkuri still failing
```
> ng2-uploader@1.5.7 postinstall /opt/git/ionic2/node_modules/ng2-uploader
> ngc -p tsconfig.json

Error: Error Cannot find type definition file for 'node'.
    at Object.check (/opt/git/ionic2/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Object.main (/opt/git/ionic2/node_modules/@angular/tsc-wrapped/src/main.js:26:15)
    at Object.<anonymous> (/opt/git/ionic2/node_modules/@angular/compiler-cli/src/main.js:14:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
Compilation failed
ionic-chat-lonje@ /opt/git/ionic2
├── UNMET PEER DEPENDENCY @angular/common@2.1.1
├── @angular/compiler@2.1.1
├─┬ @angular/compiler-cli@2.1.1
│ ├─┬ @angular/tsc-wrapped@0.3.0
│ │ └─┬ tsickle@0.1.7
│ │   └─┬ source-map-support@0.3.3
│ │     └── source-map@0.1.32
│ ├── minimist@1.2.0
│ └── reflect-metadata@0.1.8
├── UNMET PEER DEPENDENCY @angular/core@2.1.1
```

**Comment by jkuri** [comment]
did you run `npm install` again?

**Comment by theromis** [comment]
yes I did, the problem that I don't have ngc in the node_modules

**Comment by jkuri** [comment]
please try `rm -rf node_modules && npm install` again. there's a `"@angular/compiler-cli": "^2.2.3"` in package.json so it should be installed.

**Comment by theromis** [comment]
I did it multiple times
```
➜  ionic2 git:(master) ✗ rm -rf node_modules && npm install
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-sass@3.10.1 install /opt/git/ionic2/node_modules/node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.1/linux-x64-48_binding.node
Binary downloaded and installed at /opt/git/ionic2/node_modules/node-sass/vendor/linux-x64-48/binding.nodede:

> node-sass@3.10.1 postinstall /opt/git/ionic2/node_modules/node-sass
> node scripts/build.js

"/opt/git/ionic2/node_modules/node-sass/vendor/linux-x64-48/binding.node" exists.
 testing binary.
Binary is fine; exiting.

> ng2-uploader@1.5.7 postinstall /opt/git/ionic2/node_modules/ng2-uploader
> ngc -p tsconfig.json

Error: Error Cannot find type definition file for 'node'.
    at Object.check (/opt/git/ionic2/node_modules/@angular/tsc-wrapped/src/tsc.js:31:15)
    at Object.main (/opt/git/ionic2/node_modules/@angular/tsc-wrapped/src/main.js:26:15)
    at Object.<anonymous> (/opt/git/ionic2/node_modules/@angular/compiler-cli/src/main.js:14:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
Compilation failed
ionic-chat-lonje@ /opt/git/ionic2
├── @angular/common@2.1.1
├── @angular/compiler@2.1.1
├─┬ @angular/compiler-cli@2.1.1
│ ├─┬ @angular/tsc-wrapped@0.3.0
...
```

**Comment by jkuri** [comment]
okay, try `npm install @types/node --save-dev`

**Comment by theromis** [comment]
BTW: this is my `package.json`
```JSON
{
  "name": "ionic-chat-lonje",
  "author": "Lonje",
  "homepage": "https://chat.lonje.com/",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build --dev",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.1.1",
    "@angular/compiler": "2.1.1",
    "@angular/compiler-cli": "2.1.1",
    "@angular/core": "2.1.1",
    "@angular/forms": "2.1.1",
    "@angular/http": "2.1.1",
    "@angular/platform-browser": "2.1.1",
    "@angular/platform-browser-dynamic": "2.1.1",
    "@angular/platform-server": "2.1.1",
    "@ionic/storage": "1.1.6",
    "@types/jasmine": "^2.5.38",
    "@types/socket.io-client": "1.4.27",
    "angular2-jwt": "0.1.23",
    "angular2-moment": "^1.0.0-beta.rc.1",
    "angularfire2": "^2.0.0-beta.6",
    "ionic-angular": "2.0.0-rc.3",
    "ionic-native": "2.2.3",
    "ionicons": "3.0.0",
    "ng2-tag-input": "^0.4.4",
    "ng2-uploader": "^1.5.7",
    "rxjs": "5.0.0-beta.12",
    "socket.io-client": "1.5.0",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.45",
    "typescript": "2.0.6"
  }
}
```

**Comment by theromis** [comment]
uh, that helped
thank you
`npm install @types/node --save-dev` !!!!!!

**Pull request closed without merging**
