### PR TITLE
adjustments for angular rc.1 build

### PR DESCRIPTION
**Pull request by robkrause**
adjusted the imports and added typings to be able to built for angular 2 rc.1

### CODE REVIEW

**Comment by justme1** [comment]
why isn't this merged yet?

**Comment by 5amfung** [comment]
@robkrause Might as well bump it to RC2.

@jkuri Please merge when you get a chance.

**Comment by jkuri** [comment]
sorry guys for the late response. I've been "out" lately :) merging...

**Comment by 5amfung** [comment]
@jkuri Thanks very much.  I think npmjs still has the old version.

**Comment by spartaksun** [comment]
Using "npm install ng2-uploader" I`m getting a previous version

**Comment by jkuri** [comment]
New version published (0.5.2).

**Pull request merged**
