### PR TITLE
add authToken and fieldName examples

### PR DESCRIPTION
**Pull request by klitynski**
I added simple examples of options.authToken and options.fieldName -- extend those if you will. :)

### CODE REVIEW

**Comment by jkuri** [comment]
That would be fine. Thank you. I can add you as a collaborator, so you will have push access to repository if you would like to? But please provide examples/documentation when developing further.

**Comment by klitynski** [comment]
Okay, no problem.

**Comment by jkuri** [comment]
Here you go. Thanks for helping.

**Comment by klitynski** [comment]
Thanks for making it in the first place. ;) It's pretty helpful.

**Pull request merged**
