### PR TITLE
Add fieldReset parameters

### LINKED ISSUE #9: Can't upload the same file twice
When uploading the same file again - even after switching to another view (e.g. component) and back again - nothing happens.

It is probably intended behavior when the uploader is visible and you just upload the same file again (you can see that in the demo site). But in my case I switch to another component (i.e. click a menu button and go to another view via routing) and then navigate to the upload component again to upload the same file. Nothing happens. Can I maybe reset the uploader in some way when my component is constructed, as a workaround?

### PR DESCRIPTION
**Pull request by tb**
* Fix #9 Can't upload the same file twice

### CODE REVIEW

**Comment by jkuri** [comment]
@tb thanks. merging.

**Comment by tb** [comment]
@jkuri thanks! Will you update npm package?

BTW What could greatly improve people contributions would be to include demo app in this repository and add task or script to publish it to gh-pages branch.

**Comment by jkuri** [comment]
woops, forgot to publish. just did right now. I think demo app shouldn't be included in the source of this module because it will increase the install time.

**Comment by vitorguerreiro** [comment]
Dont fixed to me :/

**Comment by JamshedLatipov** [comment]
Hello guys, i'm trying to repeat upload with same files but it does not work for me could you help.

Thank you in advance.

it is my options.

```
ngOnInit() {
    let opt = {
      url: `${window.location.protocol}//${window.location.host}/api/UploadImage`,
      filterExtensions: true,
      allowedExtensions: ['jpg', 'png', 'jpeg'],
      data: { id: 0 },
      autoUpload: false,
      fieldName: this.inputName,
      fieldReset: true,
      maxUploads: 2,
      method: 'POST',
      previewUrl: true,
      withCredentials: false
    };
    this.options = new NgUploaderOptions(opt);
    this.inputUploadEvents = new EventEmitter<string>();
  }

  startUpload(id: number) {
    this.options.data.id = id;
    return this.inputUploadEvents.emit('startUpload');
  }
```

**Pull request merged**
